We can use to following code to compile all the generated dataset in a dataframe

In [14]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

%matplotlib inline

In [88]:
file_path = r"C:\Users\ADITI\Documents\Ansys 2019 R1\1_0.33_ellipse_10deg_Re1000\fft_1000_cl"
data = pd.read_csv(file_path, skiprows= 4, header= None, sep= "\t")
data.columns = ['frequency', 'spectral_amplitude']

In [89]:
freq_m = data["frequency"][data["spectral_amplitude"].idxmax()]
print(f"freq_m, {freq_m}")

# parameters
init_veloity = 0.001
Re = 1000

major_axis = 1
minor_axis = 0.33
aspect_ratio = 3
angle_of_attack = 10

strouhal_number = float(freq_m)*major_axis/init_veloity
print(f"strouhal_number, {strouhal_number}")

freq_m, 4.7616780e-07
strouhal_number, 0.0004761678

In [91]:
# Read the existing dataset
# dataset = pd.DataFrame(columns = ['major_axis', 'minor_axis', 'Aspect_Ratio', 'init_velocity','Angle_of_attack','Reynolds_Number', 'freq_m', 'Strouhal_Number'])
dataset = pd.read_csv('dataset.txt', sep= '\t')
dataset

,Unnamed: 0,major_axis,minor_axis,Aspect_Ratio,init_velocity,Angle_of_attack,Reynolds_Number,freq_m,Strouhal_Number
0,0,1,1.00,1,0.0001,0,100,1.999667e-05,0.199967
1,1,1,1.00,1,0.0005,0,500,1.166472e-04,0.233294
2,2,1,1.00,1,0.0010,0,1000,2.500000e-04,0.250000
3,3,1,0.50,2,0.0001,0,100,0.000000e+00,0.000000
4,4,1,0.50,2,0.0005,0,500,1.749562e-04,0.349912
5,5,1,0.50,2,0.0010,0,1000,3.713755e-04,0.371376
6,6,1,0.50,2,0.0001,5,100,0.000000e+00,0.000000
7,7,1,0.50,2,0.0005,5,500,7.142347e-07,0.001428
8,8,1,0.50,2,0.0010,5,1000,3.666492e-05,0.036665
9,9,1,0.50,2,0.0001,10,100,0.000000e+00,0.000000
10,10,1,0.50,2,0.0005,10,500,8.332639e-07,0.001667
11,11,1,0.50,2,0.0010,10,1000,5.555247e-07,0.000556
12,12,1,0.33,3,0.0001,0,100,0.000000e+00,0.000000
13,13,1,0.33,3,0.0005,0,500,0.000000e+00,0.000000
14,14,1,0.33,3,0.0010,0,1000,3.349832e-05,0.033498
15,15,1,0.33,3,0.0001,5,100,0.000000e+00,0.000000
16,16,1,0.33,3,0.0005,5,500,7.142347e-07,0.001428
17,17,1,0.33,3,0.0010,5,1000,4.761678e-07,0.000476
18,18,1,0.33,3,0.0001,10,100,0.000000e+00,0.000000
19,19,1,0.33,3,0.0005,10,500,7.142347e-07,0.001428
20,20,1,0.33,3,0.0010,10,1000,4.761678e-07,0.000476

In [90]:
# Adding the new data to the dataset
new_row = pd.DataFrame({'major_axis': [major_axis], 'minor_axis': [minor_axis], 'Aspect_Ratio': [aspect_ratio], 'init_velocity': [init_veloity], 'Angle_of_attack': [angle_of_attack],'Reynolds_Number': [Re], 'freq_m': [freq_m], 'Strouhal_Number': [strouhal_number]})
dataset = pd.concat([dataset, new_row], ignore_index=True)
dataset.to_csv('dataset.txt', sep= '\t', index= True)
dataset

,major_axis,minor_axis,Aspect_Ratio,init_velocity,Angle_of_attack,Reynolds_Number,freq_m,Strouhal_Number
0,1,1,1,0.0001,0,100,1.9996667e-05,0.199967
1,1,1,1,0.0005,0,500,1.1664722e-04,0.233294
2,1,1,1,0.0010,0,1000,2.5000001e-04,0.250000
3,1,0.5,2,0.0001,0,100,0.0000000e+00,0.000000
4,1,0.5,2,0.0005,0,500,1.7495625e-04,0.349912
5,1,0.5,2,0.0010,0,1000,3.7137550e-04,0.371376
6,1,0.5,2,0.0001,5,100,0.0000000e+00,0.000000
7,1,0.5,2,0.0005,5,500,7.1423472e-07,0.001428
8,1,0.5,2,0.0010,5,1000,3.6664922e-05,0.036665
9,1,0.5,2,0.0001,10,100,0.0000000e+00,0.000000
10,1,0.5,2,0.0005,10,500,8.3326387e-07,0.001667
11,1,0.5,2,0.0010,10,1000,5.5552471e-07,0.000556
12,1,0.33,3,0.0001,0,100,0.0000000e+00,0.000000
13,1,0.33,3,0.0005,0,500,0.0000000e+00,0.000000
14,1,0.33,3,0.0010,0,1000,3.3498323e-05,0.033498
15,1,0.33,3,0.0001,5,100,0.0000000e+00,0.000000
16,1,0.33,3,0.0005,5,500,7.1423472e-07,0.001428
17,1,0.33,3,0.0010,5,1000,4.7616780e-07,0.000476
18,1,0.33,3,0.0001,10,100,0.0000000e+00,0.000000
19,1,0.33,3,0.0005,10,500,7.1423472e-07,0.001428
20,1,0.33,3,0.0010,10,1000,4.7616780e-07,0.000476

In [93]:
dataset.drop(columns= ['Unnamed: 0'], inplace= True)
# dataset.drop(0, inplace= True)
dataset.to_csv('dataset.txt', sep= '\t', index= True)
dataset

,major_axis,minor_axis,Aspect_Ratio,init_velocity,Angle_of_attack,Reynolds_Number,freq_m,Strouhal_Number
0,1,1.00,1,0.0001,0,100,1.999667e-05,0.199967
1,1,1.00,1,0.0005,0,500,1.166472e-04,0.233294
2,1,1.00,1,0.0010,0,1000,2.500000e-04,0.250000
3,1,0.50,2,0.0001,0,100,0.000000e+00,0.000000
4,1,0.50,2,0.0005,0,500,1.749562e-04,0.349912
5,1,0.50,2,0.0010,0,1000,3.713755e-04,0.371376
6,1,0.50,2,0.0001,5,100,0.000000e+00,0.000000
7,1,0.50,2,0.0005,5,500,7.142347e-07,0.001428
8,1,0.50,2,0.0010,5,1000,3.666492e-05,0.036665
9,1,0.50,2,0.0001,10,100,0.000000e+00,0.000000
10,1,0.50,2,0.0005,10,500,8.332639e-07,0.001667
11,1,0.50,2,0.0010,10,1000,5.555247e-07,0.000556
12,1,0.33,3,0.0001,0,100,0.000000e+00,0.000000
13,1,0.33,3,0.0005,0,500,0.000000e+00,0.000000
14,1,0.33,3,0.0010,0,1000,3.349832e-05,0.033498
15,1,0.33,3,0.0001,5,100,0.000000e+00,0.000000
16,1,0.33,3,0.0005,5,500,7.142347e-07,0.001428
17,1,0.33,3,0.0010,5,1000,4.761678e-07,0.000476
18,1,0.33,3,0.0001,10,100,0.000000e+00,0.000000
19,1,0.33,3,0.0005,10,500,7.142347e-07,0.001428
20,1,0.33,3,0.0010,10,1000,4.761678e-07,0.000476

In [94]:
dataset = pd.read_csv('dataset.txt', sep= '\t')
dataset.head()

,Unnamed: 0,major_axis,minor_axis,Aspect_Ratio,init_velocity,Angle_of_attack,Reynolds_Number,freq_m,Strouhal_Number
0,0,1,1.0,1,0.0001,0,100,0.000020,0.199967
1,1,1,1.0,1,0.0005,0,500,0.000117,0.233294
2,2,1,1.0,1,0.0010,0,1000,0.000250,0.250000
3,3,1,0.5,2,0.0001,0,100,0.000000,0.000000
4,4,1,0.5,2,0.0005,0,500,0.000175,0.349912